TARGET= LeoBlinky2018

CH554_SDCC= /c/Users/matt/Blinkinlabs-Repos/ch554_sdcc

EXTRA_FLAGS=

C_FILES= \
	main.c \
	icn2053.c \
	uart0_int.c \
	uart1_int.c \
	circular_buffer.c \
	$(CH554_SDCC)/include/debug.c

pre-flash:
	

include $(CH554_SDCC)/examples/Makefile.include
